### ISSUE TITLE
Transfer Existing Repo

### ISSUE THREAD

**Issue by Sourish1997** [ACM-VIT/acmvit_blog#2]
Delete this repository. Push your changes to your existing repository and then transfer the repository to ACM-VIT.

**Comment by PrateekRanjanSingh** [comment]
This is actually the ACM-VIT's repo only so I am not authorized to delete this repo. Though I have pushed the changes to this repo.

**Comment by Sourish1997** [comment]
I've given you admin access for the repo. Please do the needful.
